---
title: "Data visualization"
author: "Sidsel Louise Domazet"
date: "3/3/2022"
output: word_document
---

```{r setup, include=FALSE}
source(here::here("R/package-loading.R"))
load(here::here("data/nhanes_small.rda"))
```

# One variable plots

```{r continuous-variables}
ggplot(nhanes_small, aes(x = bmi)) +
    geom_density(na.rm = TRUE)
ggplot(nhanes_small, aes(x = bmi)) +
    geom_histogram()
```

```{r discrete-variables}
ggplot(nhanes_small, aes(x = diabetes)) +
    geom_bar()
```

```{r}
nhanes_tidied <- nhanes_small %>% 
    filter(!is.na(diabetes), !is.na(education))
nhanes_tidied %>% 
    count(diabetes)
ggplot(nhanes_tidied, aes(x = diabetes)) +
    geom_bar()

```
# Plotting two variables

```{r 2-continuous-variables}
bmi_bp <- ggplot(nhanes_tidied, aes(x = bmi, y = bp_sys_ave))

bmi_bp + 
    geom_point()

bmi_bp + 
    geom_point() +
    geom_smooth()
```

```{r}
two_discrete <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, fill = education))

two_discrete + 
    geom_bar(position = position_dodge())
```

# Mixed data 

```{r discrete-continuous-variables}
two_mixed <- nhanes_tidied %>% 
    ggplot(aes(x = diabetes, y = bmi))

two_mixed +
    geom_boxplot() 

two_mixed + 
    geom_jitter()

two_mixed + 
    geom_violin()
```

# Exercise to make plots with one or two variables

```{r exercise 8.5}
# Use the original NHANES dataset
library(NHANES)
nhanes_full_tidied <- NHANES %>% 
    rename_with(snakecase::to_snake_case) %>% 
    rename(sex = gender) %>% 
    filter(!is.na(diabetes), !is.na(education))

# 1a. Distribution of age
ggplot(nhanes_full_tidied, aes(x = age)) +
    geom_density(na.rm = TRUE)
    
# 1b. Distribution of age of diabetes diagnosis
ggplot(nhanes_full_tidied, aes(x = diabetes_age)) +
    geom_histogram()

# 2a. Number of people who smoke now
ggplot(nhanes_full_tidied, aes(x = smoke_now)) +
    geom_bar(na.rm = TRUE)

# 2b. Number of people who are physically active
ggplot(nhanes_full_tidied, aes(x = phys_active)) +
    geom_bar()

# 3a. BMI in relation to systolic blood pressure
ggplot(___, aes(x = ___, y = ___)) +
    ___()

# 3b. BMI relation to diastolic blood pressure
ggplot(___, aes(x = ___, y = ___)) +
    ___()
    
# 4. Physically active people with or without diabetes
ggplot(___, aes(x = ___, fill = ___)) +
    ___(___ = ___())

# 5. Poverty levels between those with or without diabetes
ggplot(___, aes(x = ___, y = ___)) +
    ___()
```

# 

